backbone:
  foundation_root: /data/jsy/Fast-FoundationStereo
  checkpoint_path: /data/jsy/Fast-FoundationStereo/weights/20-30-48/model_best_bp2_serialize.pth
  feature_names: [feat_04, feat_32]
  freeze: true
  valid_iters: 4
  max_disp: 192
  optimize_build_volume: pytorch1

dataset:
  roots:
    - /data/jsy/Fast-FoundationStereo/lerobot_dataset_clean
    - /data/jsy/Fast-FoundationStereo/lerobot_dataset_randomized
  image_size: [256, 320]
  camera_pairs:
    - [observation.images.head_camera_left, observation.images.head_camera_right]
    - [observation.images.front_camera_left, observation.images.front_camera_right]
    # - [observation.images.left_camera_left, observation.images.left_camera_right]
    # - [observation.images.right_camera_left, observation.images.right_camera_right]
  action_normalization:
    method: quantile
    normalize_indices: [0, 1, 2, 8, 9, 10]
    stats:
      q01: [-0.03362764045596123, -0.06750572472810745, -0.0010842629708349705, 0.9550998210906982, -0.04507680609822273, -0.005762048531323671, -0.04253140091896057, 0.0, -0.03371812775731087, -0.0005596106639131904, -0.0010518922936171293, 0.9561926126480103, -0.0005458113737404346, -0.00557631254196167, -0.05721928924322128, 0.0]
      q99: [0.09689392149448395, 0.00040638691280037165, 0.07575738430023193, 1.0, 0.0018149430397897959, 0.29106417298316956, 0.05870910733938217, 1.0, 0.09757352620363235, 0.06443507969379425, 0.07772304862737656, 1.0, 0.0438656285405159, 0.28803691267967224, 0.03714333102107048, 1.0]

policy:
  num_history_frames: 2
  action_horizon: 8
  action_dim: 16
  state_dim: 16
  use_disparity: true
  disparity_ablation: none

head:
  type: rdt
  condition_token_dim: 256
  feature_queries_per_scale: 2
  disp_queries: 4
  spatial_query_num_heads: 8
  mlp:
    hidden_dim: 512
    num_blocks: 10
    dropout: 0.1
  rdt:
    hidden_size: 256
    depth: 4
    num_heads: 8
    num_kv_heads: 8
    norm_eps: 1.0e-5
    multiple_of: 256
    ffn_dim_multiplier:
    use_flash_attn: true
    num_register_tokens: 4
    num_inference_steps: 10
    sample_init: zeros
    act_adaptor: mlp3x_silu
    state_adaptor: mlp3x_silu
    img_adaptor: linear
    dtype: float32

train:
  output_dir: outputs/rdt_v1_mixed_zeros_init
  epochs: 50
  batch_size: 2
  num_workers: 4
  lr: 3e-5
  weight_decay: 0.1
  amp: true
  suppress_dynamo_errors: true
  log_interval: 50
  save_ckpt_interval: 10000
  resume_from:

visualization:
  query_attention:
    enabled: false
    mode: all
    sources: all
    view: all
    time: -1
    query: all
    fps: 10
    alpha: 0.45
    max_frames: 200
