backbone:
  foundation_root: /data/jsy/Fast-FoundationStereo
  checkpoint_path: /data/jsy/Fast-FoundationStereo/weights/20-30-48/model_best_bp2_serialize.pth
  feature_names: [feat_04, feat_32]
  freeze: true
  valid_iters: 4
  max_disp: 192
  optimize_build_volume: pytorch1

dataset:
  type: robotwin-stereo-lerobot
  root: /data/jsy/Fast-FoundationStereo/lerobot_dataset_clean
  episode_indices: [0]
  image_size: [256, 320]
  camera_pairs:
    - [observation.images.head_camera_left, observation.images.head_camera_right]
    - [observation.images.front_camera_left, observation.images.front_camera_right]
    # - [observation.images.left_camera_left, observation.images.left_camera_right]
    # - [observation.images.right_camera_left, observation.images.right_camera_right]
  action_normalization:
    method: quantile
    normalize_indices: [0, 1, 2, 8, 9, 10]
    stats:
      q01: [-0.03916368633508682, -0.09087245911359787, -0.001716530998237431, 0.9554034471511841, -0.051685038954019547, -0.005511453375220299, -0.053018439561128616, 0.0, -5.367194830796507e-07, -8.99987142588543e-08, -5.3665138999292594e-09, 1.0, -3.075579684264085e-07, -4.609865754900966e-06, -6.854533580735733e-07, 1.0]
      q99: [0.12623801827430725, 0.0008629377116449177, 0.10201482474803925, 1.0, 0.0015613483265042305, 0.29007861018180847, 0.06840682029724121, 1.0, 5.989971185726972e-08, 1.516739587259508e-07, 2.8067827315680915e-06, 1.0, 9.843553243626957e-07, 9.384382337884745e-08, 1.947882992681116e-06, 1.0]

policy:
  num_history_frames: 2
  action_horizon: 8
  action_dim: 16
  state_dim: 16
  use_disparity: true
  disparity_ablation: none

head:
  type: mlp
  condition_token_dim: 256
  feature_queries_per_scale: 2
  disp_queries: 4
  spatial_query_num_heads: 8
  mlp:
    hidden_dim: 512
    num_blocks: 10
    dropout: 0.1
  rdt:
    hidden_size: 256
    depth: 4
    num_heads: 8
    num_inference_steps: 100

train:
  output_dir: outputs/mlp_query_overfit500_new
  epochs: 500
  batch_size: 2
  num_workers: 0
  lr: 3.0e-5
  weight_decay: 0.1
  amp: true
  suppress_dynamo_errors: true
  log_interval: 50
  save_ckpt_interval: 3000
  resume_from: 

visualization:
  query_attention:
    enabled: true
    mode: all
    sources: all
    view: all
    time: -1
    query: all
    fps: 10
    alpha: 0.45
    max_frames: 200
