backbone:
  type: waft-based
  waft_root: /data/jsy/WAFT-Stereo
  config_path: /data/jsy/WAFT-Stereo/configs/SynLarge/DAv2S-4.yaml
  checkpoint_path: /data/jsy/WAFT-Stereo/weights/SynLarge/DAv2S-4.pth
  feature_names: [delta_block12]
  freeze: true
  amp_dtype: bfloat16
  max_disp: 800

dataset:
  type: robomimic-stereo-lerobot
  root: /data/jsy/robomimic/robomimic_lerobot_square_dataset
  image_size: [224, 224]
  num_episodes: 100
  camera_pairs:
    - [observation.images.agentview_left, observation.images.agentview_right]
    - [observation.images.robot0_eye_in_hand_left, observation.images.robot0_eye_in_hand_right]
  action_normalization:
    # method: quantile
    # normalize_indices: [0, 1, 2, 3, 4, 5, 6]
    # stats:
    #   q01: [-0.5420234875193051, -0.49978102449809264, -0.7431031955698542, -0.07038834379857999, -0.10083929680221491, -0.25879100838619457, -1.0]
    #   q99: [0.9970069651864254, 0.7671304940362492, 0.9481036908195938, 0.07606787359307764, 0.15165477592950483, 0.27189579713040773, 0.9999922927457302]

policy:
  num_history_frames: 2
  observation_horizon: 2
  action_horizon: 8
  prediction_horizon: 16
  action_dim: 7
  state_dim: 23

adapter:
  type: spatial_query
  feature_names: auto
  token_dim: 256
  queries_per_feature: 2
  num_heads: 8
  flatten: true

head:
  type: diffusion_unet
  diffusion_unet:
    diffusion_step_embed_dim: 256
    down_dims: [256, 512, 1024]
    kernel_size: 5
    n_groups: 8
    ddpm:
      num_train_timesteps: 100
      num_inference_timesteps: 100
      beta_schedule: squaredcos_cap_v2
      clip_sample: true
      prediction_type: epsilon

train:
  output_dir: outputs/waft_dp_hidden
  epochs: 5000
  epoch_every_n_steps: 100
  batch_size: 16
  num_workers: 4
  lr: 1e-4
  weight_decay: 1.0e-6
  scheduler_type: cosine
  warmup_steps: 500
  num_cycles: 0.5
  amp: true
  suppress_dynamo_errors: true
  log_interval: 50
  save_ckpt_interval: 5000
  resume_from:
  ema:
    enabled: true
    power: 0.75
    inv_gamma: 1.0
    max_decay: 0.9999

visualization:
  query_attention:
    enabled: false
    mode: all
    sources: all
    view: all
    time: -1
    query: all
    fps: 10
    alpha: 0.45
    max_frames: 200
